### ISSUE TITLE
#2. PC와 VR 애니메이션 구분 문제

### ISSUE THREAD

**Issue by DPRLive** [DPRLive/FanMeetingDemo#3]
멀티 환경에서 실행했을때, 
자신이 PC라면 모든 플레이어가 PC Anim Class가 적용되고
자신이 VR이라면 모든 플레이어가 VR Anim Class가 적용됨.

- VR캐릭터와 PC캐릭터를 아예 분리
- Anim Class를 합병
- Proxy별 프로그래밍

셋 중에 하나의 방법을 적용해보거나 다 안되면 새로운 방법을 모색하여 해결해야할듯.

**Comment by DPRLive** [comment]
- BasePawn/ PC / VR 캐릭터를 분리
-- 분리하면서 Collision FanmeetPlayer 프리셋을 만들어 적용하였음.
- 클라이언트의 BasePawn에서 요청 -> 서버에서 다른 캐릭터로 Possess 
위 방식으로 일단 해결되었으나 
데디케이트에서도 잘 작동할지는 테스트가 필요함.

**Comment by joung45387** [comment]
데디 서버에서 정확히 무엇을 테스트해야하고 어떤 테스트 결과를 얻어내야 하는지 알려주면 테스트 해드림.
그리고 uproject로 프로젝트 생성하려고 하니까  vr IK 플러그인 필요하다면서 프로젝트 생성이 안됨. 이 부분은 그냥 파일 통째로 압축해서 공유 가능한지.

**Comment by DPRLive** [comment]
테스트 해야하는 부분은 
데디 서버에서 VR/PC 전용 캐릭터가 따로 스폰이 가능한지,
VR/PC용 애니메이션이 잘 구분되어 출력하는지,
VR 트래킹이 잘 작동되고 상대에게도 잘 보이는지
3가지인데 VR이 있어야 되는 부분이라 준혁이 학교에 오면 연구실에 데디서버 열어달라고 할 생각이긴함.

VR IK 플러그인은 마켓플레이스에서 엔진에 직접 설치 하는거라 아마 압축파일로 공유해도 안될듯?
언리얼 아이디를 알려줘서 거기에 설치 하거나 해야할듯.

**Comment by joung45387** [comment]
테스트를 그래픽카드 달려있는 컴퓨터로 진행할것 아님? 
만약 빌드된것으로 테스트 할거 아니면 play 옵션중에 play as client였나? 이게 데디로 플레이하는것과 유사해서 테스트는 이걸로 하면 될듯. 내가 직접 테스트할땐 이 옵션으로 했음. 클라이언트 2개이상 써서. 그리고 빌드된걸로 테스트하고싶으면 패키지로 빌드해서 줌. 플러그인은 엔진폴더 들어가면 플러그인 저장된곳 있음 거기서 ik만 압축해서 주면됨. 내가 지금 쓰고있는 ue4는 직접 빌드한거라 에픽스토어에서 설치가 불가능해서 플러그인을 직접 옮겨서 해야함.

**Comment by DPRLive** [comment]
Play as client로 계속 테스트 해오긴 했는데, 데디랑 유사하다면 일단 따로 테스트 없이 이거에 맞춰서 진행 하도록 함.
플러그인은 압축해서 구글 드라이브에 올리고 링크 보냄.
